version: '3.8'

services:
  web:
    build: .
    container_name: quiz_web_admin
    ports:
      - "7903:7903"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7903"]
